# .streamlit/secrets.toml
[secrets]
HF_API_KEY = "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"
REPLICATE_API_TOKEN = "r8_YYxZex1m67RJYeCMRuaOrByS5AQWEnv0YHNLn"
FAL_KEY = "eeeaa026-34ae-4552-92d5-fe623c8d6c3d:6e282f88ced81f69b177189d1384c30e"
